### PR TITLE
TCP Communication Protocol Version 0.0.1 (Judge <-> Runner)

### PR DESCRIPTION
**Pull request by andreitudorp**
This is the first version of the TCP communication between the Judge and Runner.

Some information about the protocol:

Judge - The TCP server
Runner - The TCP client

The protocol before sending a message it first sends the size of it. If the runner loses the connection with the judge, the runner will stop all running threads and will try to reconnect. 

You can test the protocol by running test_protocol.py. The test script will run indefinitely. You will have you kill the process to make it script stop.

**!The version of the protocol must match to establish a connection!**

### TODO:
- implement START command on the runner
- support for multiple commands to be ran at the same time.

### CODE REVIEW

**Comment by ThomasNagel** [comment]
The code looks very good! I really like the command design pattern that you used. Seems like a clean way to properly handle all the communication logic. Is there also a pr for the judge repo with the code you wrote for the judge?

**Comment by ThomasNagel** [comment]
You defined the protocol and commands in a __init__.py file. Why did you choose this package approach instead of simple imports to other standard files? I think it's a nice method, but I'm just curious about your thought process behind this choice.

**Comment by ThomasNagel** [comment]
I tested it locally and everything seems to run fine

**Comment by andreitudorp** [comment]
> The code looks very good! I really like the command design pattern that you used. Seems like a clean way to properly handle all the communication logic. Is there also a pr for the judge repo with the code you wrote for the judge?

There is no pr for the judge yet. I will tinker with the protocol a bit more and then create another PR for the judge

**Comment by andreitudorp** [comment]
> I tested it locally and everything seems to run fine



> You defined the protocol and commands in a **init**.py file. Why did you choose this package approach instead of simple imports to other standard files? I think it's a nice method, but I'm just curious about your thought process behind this choice.

I went through different iterations of the protocol and the file structure. I plan to create a file for each command and to separate those files from other and keep everything clean I opted for the package approach.

**Review by ThomasNagel — APPROVED** [review]
image

**Comment by ThomasNagel** [comment]
> > I tested it locally and everything seems to run fine
> 
> > You defined the protocol and commands in a **init**.py file. Why did you choose this package approach instead of simple imports to other standard files? I think it's a nice method, but I'm just curious about your thought process behind this choice.
> 
> I went through different iterations of the protocol and the file structure. I plan to create a file for each command and to separate those files from other. So basically, to keep everything clean I opted for the package approach.

That makes sense, I think its ready for a merge!

**Pull request merged**
